package ChatApp;


/**
* ChatApp/ChatCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 11 mars 2015 kl 17:08 CET
*/

public interface ChatCallback extends ChatCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatCallback
