package ChatApp;


/**
* ChatApp/ChatCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* den 24 mars 2015 kl 12:08 CET
*/

public interface ChatCallbackOperations 
{
  void callback (String message);
} // interface ChatCallbackOperations
